version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
