#!/bin/bash
# Disables Windows Defender Realtime Monitoring to improve build times on CI https://travis-ci.community/t/yarn-network-troubles/333/7
# I would not recommend running this on anything but CI

NODEPATH=$(where.exe node.exe)
PROJECTDIR=$(pwd)
YARNCACHE=$(yarn cache dir)
TEMPDIR=$LOCALAPPDATA\\Temp
powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
powershell Add-MpPreference -ExclusionPath ${TEMPDIR}
echo "DisableArchiveScanning..."
powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
echo "DisableBehaviorMonitoring..."
powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
echo "DisableRealtimeMonitoring..."
powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"