#!/bin/bash
# Installs the latest version of OpenSSL on Windows
# OpenSSL is required for hap-nodejs
# This script is used on CI

LATEST_VERSION=$(curl "https://raw.githubusercontent.com/slproweb/opensslhashes/master/win32_openssl_hashes.json" | jq --raw-output '.files | .[] | select(.basever | contains("1.0.2")) | select(.bits | contains(64)) | select(.light == false) | select(.installer == "exe") | .url')
echo "Downloading latest version from $LATEST_VERSION"
curl "$LATEST_VERSION" --output "/c/Win64OpenSSL.exe"
powershell.exe -Command "Start-Process \"C:/Win64OpenSSL.exe\" -ArgumentList \"/silent /verysilent /sp- /suppressmsgboxes\" -Wait"