name: Tests

on: [pull_request]

jobs:
  test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Read .node-version
      run: echo "##[set-output name=node-version;]$(cat .node-version)"
      id: node-version

    - name: Install node
      uses: actions/setup-node@v2-beta
      with:
        node-version: "${{ steps.node-version.outputs.node-version }}"

    - name: npm install
      run: npm install

    - name: Run tests
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

  e2e_tests:
    name: End-to-end tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install node version from .node-version
      shell: bash -l {0}
      run: |
        cp .node-version .nvmrc
        nvm install
        nvm use

    - name: npm install
      run: npm install

    - name: Install expect
      run: sudo apt-get install expect

    - name: Run end-to-end tests
      run: ./e2e-tests/test.sh
      timeout-minutes: 5

  check_lint:
    name: Check for linting errors using node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install node version from .node-version
      shell: bash -l {0}
      run: |
        cp .node-version .nvmrc
        nvm install
        nvm use

    - name: npm install
      run: npm install

    - name: Check for linting errors
      run: npm lint

  check_format:
    name: Check for formatting errors using node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install node version from .node-version
      shell: bash -l {0}
      run: |
        cp .node-version .nvmrc
        nvm install
        nvm use

    - name: npm install
      run: npm install

    - name: Check code format
      run: npm run format:check
